### ISSUE TITLE
Amazing work. Can bepu be used in Unity?

### ISSUE THREAD

**Issue by weihua44** [bepu/bepuphysics2#102]
Thanks!

**Comment by RossNordby** [comment]
I'm actually not sure! I haven't personally tested it in a long time.

It's .NET Standard 2.0, so in theory it *could* work, and I did hear a report that sounded like someone had it working recently, but I couldn't confirm it.

In months past, a few people have gotten it working, but with massive performance deficits. Before that, it would simply crash. There is clearly some progress being made on the runtime side of things.

If you want to give it a try, I'd love to hear the results.

**Comment by weihua44** [comment]
Thank you :-)
