### ISSUE TITLE
White screen (no graphics) in demo

### ISSUE THREAD

**Issue by Leowbattle** [bepu/bepuphysics2#107]
I compiled and ran the demo program but the window was just a white screen with no graphics.
![blank](https://user-images.githubusercontent.com/26633478/99093000-d65ceb00-25c9-11eb-9ec7-88cb0250e986.png)

I tried running the program in RenderDoc to see what the issue was and I saw that the image was being rendered, just not displayed on the screen.
![renderdoc](https://user-images.githubusercontent.com/26633478/99093092-effe3280-25c9-11eb-9020-f01939c3e2c6.png)

**Comment by RossNordby** [comment]
Well that's a new one.

1. What OS/gpu/driver version is this on? 
2. Does the OpenGL version work? (From command line in repo: `dotnet run --project Demos.GL/Demos.csproj -c ReleaseStrip`)

**Comment by Leowbattle** [comment]
1. Windows 10, Nvidia GeForce GT 755M, driver version 25.21.14.2531
2. Yes, the OpenGL version does work

**Comment by RossNordby** [comment]
That should work, and unfortunately I don't have much idea of what's causing that. Especially if renderdoc is handling it fine and not pointing out any issues.

You could try running with the debug layer on to see if anything interesting shows up:

1. Set enableDeviceDebugLayer to true: https://github.com/bepu/bepuphysics2/blob/master/Demos/GameLoop.cs#L32
2. Modify the Demos/Properties/launchSettings.json to enable native debugging:
```
{
  "profiles": {
    "Demos": {
      "commandName": "Project",
      "nativeDebugging": true
    }
  }
```
3. Run with the debugger attached.

You should get at least one warning:
`DXGI WARNING: IDXGIFactory::CreateSwapChain: Blt-model swap effects (DXGI_SWAP_EFFECT_DISCARD and DXGI_SWAP_EFFECT_SEQUENTIAL) are legacy swap effects that are predominantly superceded by their flip-model counterparts (DXGI_SWAP_EFFECT_FLIP_SEQUENTIAL and DXGI_SWAP_EFFECT_FLIP_DISCARD). Please consider updating your application to leverage flip-model swap effects to benefit from modern presentation enhancements. More information is available at http://aka.ms/dxgiflipmodel. [ MISCELLANEOUS WARNING #294: ]`
The demos use an older flip mode for legacy reasons. You could try changing the SwapEffect to FlipDiscard here: https://github.com/bepu/bepuphysics2/blob/master/DemoRenderer/RenderSurface.cs#L53

Changing that breaks older OS compatibility, though, so I can't change it on master.

**Comment by Leowbattle** [comment]
I did get that warning, but there was also another warning after it:
`DXGI WARNING: IDXGIFactory::CreateSwapChain: DXGI_SWAP_CHAIN_DESC.OutputWindow is not a valid window handle. [ MISCELLANEOUS WARNING #65: ]`

I tried changing SwapEffect to FlipDiscard and FlipSequential but they caused a crash:
`An unhandled exception of type 'SharpDX.SharpDXException' occurred in SharpDX.dll
HRESULT: [0x80070005], Module: [General], ApiCode: [E_ACCESSDENIED/General access denied error], Message: Access is denied.`

Also, as an aside, to be able to use the DXGI flip model on master couldn't you check at runtime for flip model support and then fall back on the old model for compatibility?

**Comment by RossNordby** [comment]
That error confirms the expected failure, but unfortunately I don't have any good recommendations for further remote debugging. I can't reproduce it locally on any machine, so there's probably some relevant fiddly little detail in the environment that's a necessary condition for triggering it. Is there anything nonstandard about the environment? Maybe an unusual monitor configuration or an older version of windows 10 (or the opposite, a bleeding edge build)?

>Also, as an aside, to be able to use the DXGI flip model on master couldn't you check at runtime for flip model support and then fall back on the old model for compatibility?

I suppose so :P 

In the demos use case, though, there's not a strong reason to prefer the newer version until the old version starts causing its own compatibility problems.

**Comment by Leowbattle** [comment]
Well I guess that you could say that running Windows 10 on an iMac is a "fiddly little detail in the envionment"...

Thanks for the help though, being able to use the OpenGL version is good enough.

**Comment by RossNordby** [comment]
Interesting! Guess if anyone else hits this, that'll be a hint.

**Comment by haraldsteinlechner** [comment]
i just ran into supposedly the same problem, on windows 10, but with standard setup and nvidia gpu. GL works, Are there any hints on helping out on debugging this one? Thanks, harald

**Comment by RossNordby** [comment]
The diagnostic earlier in the thread might help. Trying RenderDoc/Nsight/PIX might provide more information (or fail in other interesting ways) but unfortunately this sort of thing is very difficult to diagnose remotely.
