### ISSUE TITLE
Switching state active and deactivate without remove from simulation.

### ISSUE THREAD

**Issue by ng08000** [bepu/bepuphysics2#108]
is there any way to switch the state active and deactivate to prevent other objects collide with it and freeze simulate for this object?

**Comment by RossNordby** [comment]
A body can forced asleep with `bodyReference.Awake = false`, but if something hits it it will still wake up, and sleeping operates at the level of interacting body groups. You could make a `INarrowPhaseCallbacks.AllowContactGeneration` that returns false when such a body is involved in a collision pair, stopping it from colliding with anything and ensuring that the body can be slept in isolation.

I'd expect it to be simpler to just remove it from the simulation.

**Comment by ng08000** [comment]
ok, seem like removing the object from the simulation is the on way. thanks by the way 👍
