### ISSUE TITLE
SimulationRayBatcher provides invalid CollidableReference for HitHandler

### ISSUE THREAD

**Issue by nickshalimov** [bepu/bepuphysics2#127]
Hi! I found a problem with SimulationRayBatcher in v2.3.0. When used, it provides an invalid CollidableReference for HitHandler. I found out the reason and implemented another one for my needs since the API allows it. I can’t make a pull request, but there is a patch that contains a fix.
[0001-SimulationRayBatcher-behaviour-fixed.patch.txt](https://github.com/bepu/bepuphysics2/files/6521612/0001-SimulationRayBatcher-behaviour-fixed.patch.txt)

**Comment by RossNordby** [comment]
Thanks! Fixed in 2.4.0-beta3.

Also, I should mention that the batched ray tester is a bit iffy at the moment. It provides a speedup on some intel architectures, but can be dramatically slower on other architectures (including but probably not limited to AMD Zen 1 and 2).
