### ISSUE TITLE
Random triangles randomly loosing collisions and raycasts passing through

### ISSUE THREAD

**Issue by Frooxius** [bepu/bepuphysics2#143]
Hello!

I've managed to find some more edge cases! ^^; (I'm sorry I'm throwing so many things at you, but I really appreciate your help with this!)

When testing some of our user generated content, we found out that some random parts of mesh colliders behave badly, not unlike the capsule-cylinder issue #140 - the character controller randomly bumps up and down on it.

I've noticed that sometimes even raycasts seem to pass right through certain parts of them as well, but I'm not 100 % on that one if that's something I'm doing wrong or the triangle yet, I can investigate a bit more, just mentioning this in case it helps narrow things down.

I managed to narrow the issue down to one random triangle and reproduce this in the CharacterDemo.cs, using following code:

```CSharp
 BufferPool.Take<Triangle>(1, out var triangleBuffer);

            triangleBuffer[0] = new Triangle(
                new Vector3(2832.862f, 200f, -641.5822f),
                new Vector3(2834.611f, 200.0066f, -643.3685f),
                new Vector3(2834.289f, 200f, -640.1809f));

            var mesh = new Mesh(triangleBuffer, Vector3.One, BufferPool);
            var meshCollidable = new CollidableDescription(Simulation.Shapes.Add(mesh), 0.1f);

            Simulation.Statics.Add(new StaticDescription(new Vector3(-2834f, -198, 644f), Quaternion.Identity, meshCollidable));
```

I'm also using pretty thin capsule for the character controller to reproduce this one easily: `new Capsule(0.2f, 2f)`

The triangle has pretty large offset, I'm not sure if that's the culprit here or not. I think there are some which have much smaller offsets that do this as well, I can try hunting those down if that helps. If there's a way to improve the interactions even for this case though that could help out a lot!

------------------------

Also just shoehorning something random positive here if you're interested, our community seems to be having lots of fun while testing things :D https://www.youtube.com/watch?v=Oz7t3L7xH1s

**Comment by RossNordby** [comment]
This does look like a numerical issue induced by the offset- the depths are quantized. When it's approaching or barely touching, it's showing depth values like -0.028320283 for several frames despite motion, then it snaps to 0.052883565 and bounces out.

I *should* be able to improve this fairly easily. There will still be some numerical error introduced by the large offset, but the error is currently getting compounded unnecessarily.

> Also just shoehorning something random positive here if you're interested, our community seems to be having lots of fun while testing things :D https://www.youtube.com/watch?v=Oz7t3L7xH1s

I'm glad to see others so dedicated to training for high speed ball movements.

**Comment by RossNordby** [comment]
5f2dc0b99f0dc42da76004dbc5022a2bb1cf28f6 should help.

I wasn't able to immediately reproduce issues with the ray cast. There may be some things I can do to improve it too, but it would be handy to have a reproduction for that.

**Comment by Frooxius** [comment]
Thank you so much! I've tested it and it's now working perfectly for those meshes! 

I think the Raycast thing was some goof on my end, it seems to be gone now. I think this issue is good to close!
