### ISSUE TITLE
Include XML documentation in the NuGet package

### ISSUE THREAD

**Issue by markonius** [bepu/bepuphysics2#173]
After adding the package via `dotnet add package BepuPhysics`, documentation doesn't appear on mouse over in VSCode, only the member signature.

This is usually trivially solved by adding
```
<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
<GenerateDocumentationFile>true</GenerateDocumentationFile>
```
to the .csproj.

**Comment by vpenades** [comment]
Also

```xml
 <DocumentationFile>bin\$(Configuration)\$(AssemblyName).xml</DocumentationFile>
```

**Comment by RossNordby** [comment]
[Welp, I've probably inconvenienced hundreds of people with that by now](https://pointersgonewild.com/2019/11/02/they-might-never-tell-you-its-broken/). Can you tell I don't use the bepuphysics2 nugets? :P

Should be fixed for beta8, thanks for the report!
