### ISSUE TITLE
Simple Code examples

### ISSUE THREAD

**Issue by Flori00123** [bepu/bepuphysics2#192]
Hi there and sorry for asking this question.

I played with xna 5 years ago and i always wanted to make cool games with it, also because right now the gaming industry is a big money making mess that scams users only to force them to buy there battle pass. And the problem is xna/monogame has no physics engine by default.

So i here my question, do you have simple examples? Where i can easily see how this works? All the samples i saw right now are super hard, for someone who is not that into the graphics and physics szene. 

Thank you a lot!!!

**Comment by RossNordby** [comment]
I'd recommend the [getting started](https://github.com/bepu/bepuphysics2/blob/master/Documentation/GettingStarted.md) documentation as an introduction. It explains the concepts and points into demos showing those concepts in more depth.

You don't need to pay attention to any of the graphics stuff in the demo; it's completely independent of the physics. The [demos](https://github.com/bepu/bepuphysics2/tree/master/Demos) folder contains the most relevant sample code. The [SimpleSelfContainedDemo](https://github.com/bepu/bepuphysics2/blob/master/Demos/Demos/SimpleSelfContainedDemo.cs) shows how to set up a simulation in isolation with none of the demos infrastructure.

**Comment by Flori00123** [comment]
thanks, helped me a lot
