### ISSUE TITLE
netstandard2.0 and 2.1 targeting

### ISSUE THREAD

**Issue by vpenades** [bepu/bepuphysics2#194]
I think it's been discussed before, so sorry if I bother again with an already discussed issue...

Would it be possible to let BepuPhysics multitarget netstandard2.0, netstandard2.1, net5 and net6 ?

The reasoning is that netstandard2.0 is considered a baseline for maximum compatibility _during development time_.

In our case, we are being required that all our "pure logic" libraries to target at least nestandard2.0, and then target other frameworks for optimizations.  Then, the final executable is net6.

So, performance wise, NetStandard is not really used in production (because higher versions are always picked during compilation), but it lets being referenced by lesser framework projects, which in many cases, it's very convenient for architecturing large projects.

**Comment by RossNordby** [comment]
Sorry, but this is a maintenance burden that I can't justify spending time on. It would be *possible* to do (and I believe Frooxius has been trying to maintain NS2.0 compatibility over at https://github.com/Neos-Metaverse/bepuphysics2, at least for part of 2.4 so far), but there's enough finnicky stuff all over the place that it would cost me quite a bit to support in an official capacity.

**Comment by vpenades** [comment]
I take it it's related to Runtime.Intrinsics support.

It could be possible to provide non intrinsics counterparts for netstandard, but given you're pretty much alone in the project, I fully agree with you about the maintenance burden.

So closing the issue, thanks for the reply!

**Comment by RossNordby** [comment]
A big chunk is the intrinsics, yes. There remain fallbacks for those, so tossing compilation symbols in the appropriate places would work. Unfortunately, there's a good bit of other stuff, like initialization avoidance that infects a lot of functions (Unsafe.SkipInit), plus runtime-dependent language features going forward.
