### ISSUE TITLE
Can't compile with preview nugets

### ISSUE THREAD

**Issue by vpenades** [bepu/bepuphysics2#24]
When trying to compile the project I get errors with System.Numerics.Vectors and System.Runtime.CompilerServices.Unsafe not being found.

Reverting to stable v4.4.0 versions on both packages fixes the problem.

If you don't require any feature present in the nuget previews, I would suggest to switch back to v4.4.0 nugets

**Comment by RossNordby** [comment]
Once the engine reaches alpha or any other status where I feel like it's potentially useful to other people, I'll definitely be avoiding things like this which make setup difficult. For now, though, it's useful to me to rapidly experiment with preview releases in some cases.

If you'd like to experiment with the preview nugets, you can add the preview feed to your nuget package sources: `https://dotnet.myget.org/F/dotnet-core/api/v3/index.json`

I also sometimes use preview versions of the core runtime, which is a little trickier to setup: https://github.com/dotnet/core/blob/master/daily-builds.md

**Comment by RossNordby** [comment]
In preparation for the alpha release, all the preview stuff has been dropped to stable. Things should, in theory, be able to build without a hitch on any machine with the latest version of VS2017 and the DX SDK.
