### ISSUE TITLE
Csproj project files incorrectly defined.

### ISSUE THREAD

**Issue by vpenades** [bepu/bepuphysics2#25]
I've seen this line of code and I was wondering why you need it:

```
<PropertyGroup>
    <!-- TODO: Why is this necessary? It refers to 1.6.1 rather than 2.0 without this, despite the target framework being set to 2.0 above. -->
    <NetStandardImplicitPackageVersion>2.0</NetStandardImplicitPackageVersion>
  </PropertyGroup>
```

I think it's because you have defined the project kind in a very odd way:

```
<Project>
  <!--Note workaround for macro evaluation issue.-->
  <Import Sdk="Microsoft.NET.Sdk" Project="Sdk.props" />
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <!-- ... -->
    <LangVersion>7.2</LangVersion>
  </PropertyGroup>
  <Import Sdk="Microsoft.NET.Sdk" Project="Sdk.targets" />
</Project>
```
I think if you define the project as in the default templates, you can simplify the project definition:

```
<Project Sdk="Microsoft.NET.Sdk">  
  <PropertyGroup>    
    <TargetFramework>netstandard2.0</TargetFramework>
    <!-- ... -->
    <LangVersion>7.2</LangVersion>
  </PropertyGroup> 
</Project>
```

**Comment by RossNordby** [comment]
I periodically review whether or not the bug motivating that weirdness has been fixed in the public tooling- last I checked, it wasn't. Unfortunately, without that nonstandard layout, some custom build steps fail.

I'll check the current release when I get the chance to see if these hacks are still required.

**Comment by RossNordby** [comment]
The original macro evaluation issue was still present, but I went ahead and moved to an alternate (and seemingly more future proof) form of build steps that doesn't have the same issue. And apparently the implicit-package-requiring issue disappeared at some point, so now the csproj format is more standard.

Relevant commit: c65306e5fcf38895a410dcf9b54d2897c745eb07
