### ISSUE TITLE
Does this mean that when end_point0 =new EdgeEndpoints(){A=0,B=3}, end_point1 =new EdgeEndpoints(){A=1,B=2}, their hash values are equal

### ISSUE THREAD

**Issue by zyxia** [bepu/bepuphysics2#260]
https://github.com/bepu/bepuphysics2/blob/d77ee1a33268c4439b8d1d62b5dd873724833ced/BepuPhysics/Collidables/ConvexHullHelper.cs#L414

**Comment by zyxia** [comment]
When the hash values are equal, doesn't it affect the index of the Dictionary？

**Comment by RossNordby** [comment]
Yes, but it won't break the dictionary- the hash value is allowed to collide with other entries. It's just not ideal.

This hash *could* be improved, I just didn't bother at the time.
