### ISSUE TITLE
Is there any way to bring the api level down to C#8.0

### ISSUE THREAD

**Issue by PinkFatMan** [bepu/bepuphysics2#279]
Hello, I want to use Bep in unity. But C#9 is not currently supported in Unity. I tried to make changes to C#8 but found it a lot of work. Is there any way to branch master down to C#8?

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by RossNordby** [comment]
With a large amount of effort, maybe, but you would then hit runtime incompatibilities. Until Unity finishes the CoreCLR integration, bepuphysics2 will be very slow when it runs at all. For updates, you could keep an eye on this thread: https://forum.unity.com/threads/unity-future-net-development-status.1092205/page-36
