### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Krakean** [bepu/bepuphysics2#28]
@RossNordby 
https://i.imgur.com/hkaXiNS.png
Seems like roadmap requires corrections? :)

**Comment by RossNordby** [comment]
I was hoping no one would notice.

[Definitely fixed](https://github.com/bepu/bepuphysics2/commit/b95ca0a6ac62e2fe23a1f12268350144c5a67d5b#diff-24c2abd7d3c09bb1063b347c60791cc4).

**Comment by Krakean** [comment]
>I was hoping no one would notice.

Heh. Watching too carefully for your project :)
But, may be just get rid of February and set more precise month? April, for example. :)

**Comment by RossNordby** [comment]
Alright, alright, the roadmap no longer relies on [unique definitions](https://github.com/bepu/bepuphysics2/blob/aae997438577439d0bf95289e24f8678d7a7e0ea/Documentation/roadmap.md#alpha-march-2018).

(It'll be somewhat impressive if I still miss that deadline.)

**Comment by Krakean** [comment]
@RossNordby 
>(It'll be somewhat impressive if I still miss that deadline.)

Its mostly end of march :)

**Comment by RossNordby** [comment]
So it is, so it is...

The stuff in the roadmap is done, for what it's worth; I'm just trying to squash some AVX2-only bugs that I discovered at the last second. That's what I get for developing on a 6 year old computer.

**Comment by Krakean** [comment]
@RossNordby good to know that everything is good well and roadmap is on track :) Ross, curious, since bepu2 is not yet going to stable for a while, is it possible to get some quick-to-implement speed optimizations for bepu1? Considering all that experience that you received while developing and optimizing bepu2

**Comment by RossNordby** [comment]
Unfortunately, v1 is a victim of its fundamental design. Getting big 10x+ performance improvements requires deep changes to data access patterns which are just incompatible with v1's OOPy mess.

Swapping the math library to rely on System.Numerics.Vectors would give you *some* benefit (10-40% depending on the simulation), but that would be a large enough job that I wouldn't want to delay v2 for it. (If you want to look into doing that yourself, beware- there is a nontrivial amount of manually inlined code in performance sensitive areas from back when that was a thing in the XNA Xbox360 days.)
