### ISSUE TITLE
Initializing big compound with only 1 member results in some weird internal tree error.

### ISSUE THREAD

**Issue by emelrad12** [bepu/bepuphysics2#285]
This is running bepu in debug mode, so alll assertions are on. 
I would suggest either making it throw mor sensible exception when there is only 1 item, or if possible making it work with a single one.
Here a screenshot of the error and callstack.
![image](https://github.com/bepu/bepuphysics2/assets/16389331/901e9fc9-9b6f-4fbb-9495-c0a61bf3cf3b)

**Comment by RossNordby** [comment]
Just a bug in the new binned builder's corner case; fixed in 299ed8919c6c9d976cb57c157596b5772a51f14e. Thanks for the report!

**Comment by emelrad12** [comment]
Works great, thanks for fixing it so fast.
