### ISSUE TITLE
this project can be run on macos ?

### ISSUE THREAD

**Issue by cayikubiatm** [bepu/bepuphysics2#291]
i try some times to run it on mac ,but not success.

**Comment by RossNordby** [comment]
The library is cross platform, but the demos application is only partly cross platform. I don't test or maintain the demos application for non-Windows targets, but a contributor added an OpenGL version (Demos.GL.sln) that may or may not work on mac.

**Comment by cayikubiatm** [comment]
Ok,thank you very much.
