### ISSUE TITLE
Spin/Friction Issues with the Character Demo

### ISSUE THREAD

**Issue by Vercidium** [bepu/bepuphysics2#305]
I'm having some strange issues with cylinders, where they spin quickly and take a while to fall down. I'm using the [Characters](https://github.com/bepu/bepuphysics2/tree/master/Demos/Demos/Characters) demo from this Github repo.

[Video of the issue](https://youtu.be/0EjUETWaLj4)

I've played around with different dampening, friction and spring settings but can't figure out why this is happening. I'd like the cylinder to fall down regularly, have a tiny bit of bounce, and roll around a bit.

I have the following Contact settings:
```
public bool ConfigureContactManifold<TManifold>(int workerIndex, CollidablePair pair, ref TManifold manifold, out PairMaterialProperties pairMaterial) where TManifold : unmanaged, IContactManifold<TManifold>
{
    pairMaterial = new PairMaterialProperties { FrictionCoefficient = 1.0f, MaximumRecoveryVelocity = 2, SpringSettings = new SpringSettings(30, 1) };
    Characters.TryReportContacts(pair, ref manifold, workerIndex, ref pairMaterial);
    return true;
}
```
Simulation settings:
```
simulation = Simulation.Create(bufferPool, new CharacterNarrowphaseCallbacks(characters), new DemoPoseIntegratorCallbacks(new Vector3(0, -1, 0)), new SolveDescription(10, 10));
```
Dampening settings:
```
public DemoPoseIntegratorCallbacks(Vector3 gravity) : this()
{
    Gravity = gravity;
    LinearDamping = 0.03f;
    AngularDamping = 0.03f;
}

public void PrepareForIntegration(float dt)
{
    linearDampingDt = new Vector<float>(MathF.Pow(MathHelper.Clamp(1 - LinearDamping, 0, 1), dt));
    angularDampingDt = new Vector<float>(MathF.Pow(MathHelper.Clamp(1 - AngularDamping, 0, 1), dt));
    gravityWideDt = Vector3Wide.Broadcast(Gravity * dt);
}
```
Cylinder creation:
```
var cylinder = new Cylinder(0.8f, 22.0f);
var inertia = cylinder.ComputeInertia(50.0f);
var body = BodyDescription.CreateDynamic(pos, inertia, simulation.Shapes.Add(cylinder), 0.1f);
var handle = simulation.Bodies.Add(body);
```
Terrain creation:
```
var meshShape = new Mesh(triangles, new System.Numerics.Vector3(1, 1, 1), demo.bufferPool);
var index = demo.simulation.Shapes.Add(meshShape);

var description = new StaticDescription(
    new System.Numerics.Vector3(worldPosX, 0, worldPosZ),
    System.Numerics.Quaternion.Identity,
    index
);
demo.simulation.Statics.Add(description);
```

**Comment by Vercidium** [comment]
I came across [this post](https://forum.bepuentertainment.com/viewtopic.php?t=412) that the old Bepu forums which suggested modifying the InverseInertiaTensor of the cylinder:

```
var cylinder = new Cylinder(0.8f, 22.0f);
var inertia = cylinder.ComputeInertia(50.0f);
inertia.InverseInertiaTensor.YY *= 0.1f; // <------- Fix here
var body = BodyDescription.CreateDynamic(pos, inertia, simulation.Shapes.Add(cylinder), 0.1f);
var handle = simulation.Bodies.Add(body);
```

This worked perfectly! [Video here](https://www.youtube.com/watch?v=qf3kHM0Fyhc). I then changed the SpringSettings from `(30, 1)` to `(1, 30)` to reduce how much it bounces when it lands.

[This post](https://gamedev.stackexchange.com/questions/200034/why-do-colliders-have-a-tendency-to-spin-and-develop-crazy-angular-velocity-in-u) about rigid bodies also explains why this issue occurs. Their solution was to set the angular velocity back to zero every frame, or adjust the angular drag. I don't think adjusting the drag is possible is it?

For future reference, things that didn't fix the spinning:
- Changing the mass of the cylinder
- Changing the `SpringSettings`
- Changing the `MaximumRecoveryVelocity`
- Changing the`SolveDescription` from `(10, 10)` to `(100, 100)` or `(1, 1)`

Possible workaround:
- Set the `FrictionCoefficient` so the cylinder slides down the hill

**Comment by RossNordby** [comment]
You're correct that this is related to inertia, in particular how highly nondiagonal inertias interact with angular integration. The [default demos callbacks](https://github.com/bepu/bepuphysics2/blob/1fdf7349f28c371da8a52d0b7b1ae880cec3b8b4/Demos/DemoCallbacks.cs#L31) specify `AngularIntegrationMode.Nonconserving` since it's *usually* fine, stable, and quick.

For long shapes like a tree, it's less good. Changing it to `AngularIntegrationMode.ConserveMomentumWithGyroscopicTorque` should help.

Of course, beefing up the axis of minimum inertia (by scaling down the inverse) is a perfectly cromulent workaround for games.
