### ISSUE TITLE
NullReferenceException with a large number of statics.

### ISSUE THREAD

**Issue by Hromon** [bepu/bepuphysics2#344]
![image](https://github.com/user-attachments/assets/1c5cfeee-6030-4839-abd1-b0508825530f)

This happens after 30-60 seconds. I continuously (in the main thread) create cubes of different sizes, and at the bottom there are statics with boxes 1 by 1. These statics are 1000* 1000 and they act instead of the floor. And with this configuration, the engine behaves very unstable. If you reduce the number of static, then everything comes back to normal.

**Comment by Hromon** [comment]
And it also falls here
![image](https://github.com/user-attachments/assets/e18beb51-6ec2-4f50-a6fb-68b69f3e3998)

**Comment by RossNordby** [comment]
That's a confusing place for it to fail; are the modifications to the simulation happening asynchronously with respect to the call to `Simulation.Timestep`? That'll break it in a lot of ways.

If that's not it, I may need a reproduction in the demos to narrow it down rapidly.

**Comment by Hromon** [comment]
Yes, it's work in one thread. I send demo-project, use godot 4.3.
[TestingProject.zip](https://github.com/user-attachments/files/17172619/TestingProject.zip)

**Comment by RossNordby** [comment]
I can get to that later (I have a somewhat tedious process for handling arbitrary .zips due to Unfortunate Additional Security Requirements), but if you'd like to speed me up, I could use a minimal reproduction snippet in the bepuphysics2 demos directly to narrow down possible confounders.

**Comment by Hromon** [comment]
Okay, I'll get it together now

**Comment by Hromon** [comment]
Strangely, there is no such error in the demo project, although I am sure that in godot I create and access the simulation in the same thread where it is updated

**Comment by Hromon** [comment]
Code:
```
public class StaticWorldDemo : Demo
{
    public override void Initialize(ContentArchive content, Camera camera)
    {
        camera.Position = new Vector3(-30, 40, -30);
        camera.Yaw = MathHelper.Pi * 3f / 4;
        camera.Pitch = MathHelper.Pi * 0.2f;

        Simulation = Simulation.Create(BufferPool, new DemoNarrowPhaseCallbacks(new SpringSettings(30, 1)), new DemoPoseIntegratorCallbacks(new Vector3(0, -10, 0)), new SolveDescription(8, 1));

        for (int x = -500; x < 500; x++)
            for (int z = -500; z < 500; z++)
                Simulation.Statics.Add(new StaticDescription(new RigidPose(new System.Numerics.Vector3(x, 0, z)), Simulation.Shapes.Add(new Box(1, 1, 1))));
    }

    public override void Update(Window window, Camera camera, Input input, float dt)
    {
        Simulation.Bodies.Add(BodyDescription.CreateConvexDynamic(new RigidPose(new Vector3(0, 100, 0)), 1, Simulation.Shapes, new Box(1, 1, 1)));
        Simulation.Bodies.Add(BodyDescription.CreateConvexDynamic(new RigidPose(new Vector3(100, 100, 0)), 1, Simulation.Shapes, new Box(1, 1, 1)));
        Simulation.Bodies.Add(BodyDescription.CreateConvexDynamic(new RigidPose(new Vector3(-100, 100, 0)), 1, Simulation.Shapes, new Box(1, 1, 1)));
        base.Update(window, camera, input, dt);
    }

    public override void Render(Renderer renderer, Camera camera, Input input, TextBuilder text, Font font)
    {
        text.Clear().Append("Press Z to shoot a bullet, press X to super shootie patootie!");
        renderer.TextBatcher.Write(text, new Vector2(20, renderer.Surface.Resolution.Y - 20), 16, new Vector3(1, 1, 1), font);
        base.Render(renderer, camera, input, text, font);
    }
}
```

**Comment by Hromon** [comment]
Okay, I think this is a Godot problem, thanks for the help and the engine!

**Comment by RossNordby** [comment]
Interesting! If you find out why that's happening, I'd be interested in hearing about it; I encountered some differences in performance when I tested (a long while ago) which I didn't understand. A simple repro like that failing might reveal why (e.g. it's not actually using the runtime I thought it was.)
