### ISSUE TITLE
V1 vs. V2 API Differences?

### ISSUE THREAD

**Issue by Blwnkl** [bepu/bepuphysics2#50]
I'm trying to give Bepuphysics a try, incorporating into a .Net Core 2.1 testbed project.
After gronking through a lot of V1-related samples etc., that refer to the "Space" class, I'm not seeing that exist in V2.  Unless I'm "completely" misunderstanding something, it almost looks like "Simulation" has taken over the role of "Space"?  But there are method/property differences.  I'm terribly confused!
The V1 tutorial fundamentals seemed to make sense, adding things having orientations etc. to the "space" and periodic calls to Update.  Is there a list of V1/V2 differences that might show the way? Or V2 tutorial?
Thanks for doing this project, BTW... it looks Really Awesome! 
Jim

**Comment by RossNordby** [comment]
Simulation has indeed replaced Space. More generally, v2 is a complete rewrite and is about as different from v1 as v1 is from Bullet or other physics engines. All the core concepts are there, but the APIs are quite different.

I do intend to make a concept mapping as it gets closer to release, but it doesn't exist yet. The best option at the moment is probably opening up the v2 [Demos ](https://github.com/bepu/bepuphysics2/tree/master/Demos/Demos)project and playing around with it. v2's demo set isn't quite as thorough as v1's yet, but it covers most things.

**Comment by Blwnkl** [comment]
Thanks for the quick reply!  OK, it's reassuring to know that I wasn't missing something huge! :)
I'm looking at the V2 Demos as we speak, and I expect that I'll be able to get off the ground.  The only other hurdle I had to get over was the ".Net Standard 2.0" incompatibilities with "vanilla" .Net Framework projects. Sigh.  Microsoft doesn't have to comply with the Hippocratic Oath, I suppose... ("first, do no harm!) :)
