### ISSUE TITLE
Q&A Documentation is hard to read

### ISSUE THREAD

**Issue by mcmonkey4eva** [bepu/bepuphysics2#58]
The Q&A file (here: https://github.com/bepu/bepuphysics2/blob/master/Documentation/QuestionsAndAnswers.md )
Uses this format for each question/answer:
```
##### Question?

Answer answer answer.
```
Which looks like this:
"
##### Question?

Answer answer answer.
"
Which is approximately the least visible separation of question and answer you could have chosen.

For reference, here it is with bold instead of that:
"
**Question?**

Answer answer answer.
"
I would suggest either `##`, which does this:
"
## Question?

Answer answer answer.
"
Or `###`, which does this:
"
### Question?

Answer answer answer.
"

Both of those make the separation of Question from Answer much more clear, allowing a reader to skim the page for a question they're interested in and read the answer to that (rather than struggling to find where the questions are among the answer text).

In case of display changes over time or over browser/device, here's an image of this post (as taken on Firefox on Windows 10 Desktop in January 2019).
> ![https://i.alexgoodwin.media/i/misc/11fd9c.png](https://i.alexgoodwin.media/i/misc/11fd9c.png)

**Comment by RossNordby** [comment]
> Which is approximately the least visible separation of question and answer you could have chosen.

Hmmmmmmmmmmmm... I dunno, I feel like I could have found something much worse...

([updated](https://github.com/bepu/bepuphysics2/blob/master/Documentation/QuestionsAndAnswers.md))
