### ISSUE TITLE
Assertion failed while creating convex hull for Tetrahedron

### ISSUE THREAD

**Issue by mmusu3** [bepu/bepuphysics2#73]
While attempting to create a convex hull from 4 points of a tetrahedron the assertion in `ConvexHullHelper.FindExtremeFace` fails. The last condition in the assert is false as `vertexIndices.Span.Length` is 4, `pointBundles.Length` is 1 and `Vector<float>.Count` is 8.
Here is the snippet to reproduce:
```cs
Simulation.BufferPool.Take<Vector3>(4, out var hullPoints);

hullPoints[0] = new Vector3( 1,  1, -1);
hullPoints[1] = new Vector3( 1, -1, -1);
hullPoints[2] = new Vector3(-1, -1, -1);
hullPoints[3] = new Vector3( 1, -1,  1);

var hull = new ConvexHull(hullPoints, Simulation.BufferPool, out var center);
```

**Comment by RossNordby** [comment]
Should be fixed in 9be93c049e68505294576d8257e3d463e71296b9. Thanks for the report!
