### ISSUE TITLE
V2 and VB.NET

### ISSUE THREAD

**Issue by SergeyBaryshev** [bepu/bepuphysics2#74]
(sorry for my English, it's not my native language)

I'm a VB.NET programmer.
Apparently, the second version cannot be used in VB.NET, because unsafe code and pointers are not supported in it. I can't even create a simulation because one of the arguments that implements the INarrowPhaseCallbacks interface uses a pointer to pass a value.
So it looks like I'm stuck on version 1.5, which I've successfully attached to my project.
Or... maybe is there a some solution?

BTW, I am very impressed with the demonstrations and the performance of the new version.

**Comment by RossNordby** [comment]
Unfortunately, yes, v2 has a large number of API level incompatibilities with VB. It is possible to create a compatibility/convenience layer in C# that hides the incompatible parts behind fully CLS-compliant APIs that could then be used in VB. It would come with some performance/usability tradeoffs and I don't plan to personally do it, but it is feasible.

**Comment by SergeyBaryshev** [comment]
Thanks for reply!

> It is possible to create a compatibility/convenience layer in C# that hides the incompatible parts behind fully CLS-compliant APIs that could then be used in VB.

I've thought about that, too. I think it's called a wrapper, like it hides unsafe code inside, and makes public functions compatible with VB. A good idea, but not an easy one. Unfortunately, I'm not good at C#, and this implementation could take months for me.

But thanks to you, we have the demos source code that compiles and runs in Visual Studio 2019 just perfectly. Some day, step by step, I'll do it.
