### ISSUE TITLE
Velocity of Body suddenly increased by factor 7

### ISSUE THREAD

**Issue by hitclif** [bepu/bepuphysics2#77]
Hello,
im am using BepuPhysics to simulate a fall of a geometry (body) on another geometry (static).
Here I've experienced some strange behavior: the velocity of the body fluently rises according the object falling down due the gravity. The linear velocity increment (LengthSquared) is ca. 10 per one simulation Update. However, after (in my circumstances) 246 updates, the next simulation update causes the velocity to increase in ca. 8 000 000 (linear) and 500 000 (angular).

In the image, you can see part of the output of the velocities (lengthSquare).

If it helps, I may send you the demo project with all the geometries.

![velocity](https://user-images.githubusercontent.com/12540864/63168630-fa332900-c034-11e9-861f-d140d232b508.PNG)

**Comment by RossNordby** [comment]
I'd definitely need a repro to identify the issue (ideally stripped to the bare minimum simulation that still reproduces it). 

Best guess is that it's interacting with something else that's moving rapidly. Objects in pure freefall are only affected by the pose integrator callback (and any external meddling), so the number of potential sources are very small.

**Comment by RossNordby** [comment]
One more shot in the dark- if you're tracking the body state by using an index into the active set, it could be invalidated by the body memory optimizer or other body movements. Grabbing a BodyReference using the handle (or doing the equivalent lookup manually) is required to deal with memory movement.

**Comment by hitclif** [comment]
Attached, you can find zip file with the whole solution. Basically, it's the Demos.sln from your git, I've only removed all other demos and implemented the new one to simulate gravity.
Notes:
- there's only one body falling down, thus, it can't hit any other moving body
- if I change the Scaling of the mesh (new Mesh(trianglesBuffer, Scale, bufferPool)), the behavior  changes (for Scale = Vector3.One the issue is present, for Scale = new Vector3(0.1f) the simulation is ok) - have a look at file Demos.Demos.Tools line 19 resp. 74
- my geometetries have different "orientation" - the y and z axis are interchanged. However, that shouldn't influence the simulation itself, it just look awkward in the UI

Thanks for help

[BEPU_Issue.zip](https://github.com/bepu/bepuphysics2/files/3511796/BEPU_Issue.zip)

**Comment by RossNordby** [comment]
Reproduced and looking into it. It appears to be an issue related to the triangle pair tester.

While I work on this, I strongly recommend against using mesh-mesh collisions in general. It is pretty much guaranteed to produce poor results (even without any bugs). Triangles are infinitely thin and meshes have no volume, so dynamic contacts pretty much can't work robustly. Decomposing the dynamic mesh into a (big)compound of convex hulls would avoid these issues and would likely be faster.

**Comment by RossNordby** [comment]
5c7a3cd01463045b5bce9510a6237cdd23d28bf0 should fix the main flyaway issue- turns out it wasn't the TrianglePairTester's fault after all, but rather a corner case in constraint generation.

There are still some numerical issues associated with near-90 degree large triangle-triangle collisions that I'd like to improve though.

**Comment by hitclif** [comment]
Hi, I've tested it, looks good.

Two more questions:
- when do you plan to release the nuget package update?
- you've mentioned, I should decompose Mesh to (Big)Compound. Is there a way/tools in BEPU to decompose a generic 3D mesh into Compound, or do I need to do it on myself (manually). The issue is that I don't have full control over incoming Meshes (user may create his own objects)

Thanks.

**Comment by RossNordby** [comment]
I was planning on a nuget release after getting the either the broad phase revamp or the depth refiner warm start in. Not sure when that'll be, but I might just push out a 2.0.1 for the miscellaneous things that have cropped up since the first release. I usually recommend direct source references.

The library does not contain any automatic convex decomposition functions at the moment- I punted responsibility for that over to other libraries or content programs.

**Comment by hitclif** [comment]
Speaking for myself:
- I would suggest several minor releases with bug-fixes and major release with functionality. 
- I as well prefer to reference nuget package over referencing the source code - it's absolutely ok, when the code is only at one place - your git repo.

Regarding decomposition, thanks for answer, I will look for a solution.

You've been very helpful.
Thanks
