### ISSUE TITLE
Tetrahedralizer

### ISSUE THREAD

**Issue by diwot** [bepu/bepuphysics2#78]
In the NewtDemo you mention a less dumb Tetrahedralizer variant. Can the source code of that one be downloaded somewhere?

**Comment by RossNordby** [comment]
Not at the moment-it's a bit more tightly bundled with the rest of the project that the DumbTetrahedralizer came from, and has some particular goals (it built a control cage for the mesh that obeyed surface connectivity, so places like lips could have overlapping but disconnected cells). It would take some effort to rebundle into a standalone/reasonably modern form.
