### ISSUE TITLE
NaN position with SimpleSelfContainedDemo

### ISSUE THREAD

**Issue by kascodingNL** [bepu/bepuphysics2#81]
I could send an screenshot of the error that it spews out if you add more than 1 body.

Ask for it then :)

**Comment by RossNordby** [comment]
Could you post the modified code? I cannot reproduce the issue locally.

**Comment by kascodingNL** [comment]
Yes sure! Give me some minutes!

**Comment by kascodingNL** [comment]
https://hastebin.com/efajuhehev.cs

**Comment by RossNordby** [comment]
It appears to work as expected on my machine- no NaNs or exceptions. Tried both Step variants too.

Is the frameRate being used valid? What runtime are you observing the issue on? (I'm testing on CoreCLR, but some older mono runtimes can have issues.)

**Comment by kascodingNL** [comment]
Thanks RossNordby, I will look into this this day

**Comment by kascodingNL** [comment]
Hello RossNordby,

I hope i found my runtime, could it be called Target Framework?
If yes, I am using is; .NET Framework 4.6.1

**Comment by kascodingNL** [comment]
Okay! I fixed it i think! I cloned the repository again and rebuilded it, and then it worked! Thanks for the help you gave!
