### ISSUE TITLE
Up to date NuGets

### ISSUE THREAD

**Issue by drjaydenm** [bepu/bepuphysics2#83]
Hi there, firstly I just wanted to thank you for your continued work on this library, it's great to have such a feature packed library available in .NET that is regularly maintained.

I just wanted to ask about the NuGet releases and how they are determined. At the moment, NuGet is on 2.0.0 and looks to be a snapshot of around the 21st of April. Since then there are a heap of code changes to master that look to be bug fixes and other improvements. Is there any reason these haven't been released under a minor version like 2.1.0 or something along those lines?
Thanks

**Comment by RossNordby** [comment]
>Is there any reason these haven't been released under a minor version like 2.1.0 or something along those lines?

Yes! But not a good one :P

I was originally intending to get some broad phase or convex hull updates into a '2.1', but the real reason for the lack of a recent publish is just laziness.

**Comment by RossNordby** [comment]
2.1, containing all the accumulated changes, is now packaged and released.

I should probably set up automation at some point to eliminate laziness as a concern.

**Comment by drjaydenm** [comment]
Thanks for doing that so quickly! I can definitely understand the hassles around releasing all the time so I appreciate it, wanted to get the latest in a project without having to git submodule it, or compile the DLLs manually :)
