### ISSUE TITLE
Demos not working (Errors)

### ISSUE THREAD

**Issue by CreativeHouseDotOrg** [bepu/bepuphysics2#86]
Hi

I cloned this git today and when running Demos I get these Error Messages:

![err1](https://user-images.githubusercontent.com/4038603/74449531-f9147480-4e7c-11ea-9552-88a0ed827f94.PNG)

![err2](https://user-images.githubusercontent.com/4038603/74449534-f9ad0b00-4e7c-11ea-8ca9-6427435955ce.PNG)

Am I missing dependencies? Any Help is appreciated.

Kind Regards

**Comment by RossNordby** [comment]
Creating a device in debug mode (which is what the debug configuration does by default) requires the DX SDK to be installed, which is in the Windows SDK now.

I think the vs installer will grab it for you if you install the "Game Development with C++" workload.

**Comment by CreativeHouseDotOrg** [comment]
Awesome hint thank you very much :)

I couldn't find a place to just offer you a beer so I decided to sponsor you instead! :)

Cheers!

**Comment by RossNordby** [comment]
Thanks!
