### ISSUE TITLE
Arithmetic overflow in NarrowPhase.AddBatchEntries

### ISSUE THREAD

**Issue by Bartolomeus-649** [bepu/bepuphysics2#90]
When you turn on "Check for arithmetic overflow" for the BepuPhysics project, you end up with an arithmetic overflow in [`BepuPhysics.CollisionDetection.NarrowPhase<TCallbacks>.AddBatchEntries`](https://github.com/bepu/bepuphysics2/blob/76d3398ea6c9bd47626214abd157b3dcaaf965df/BepuPhysics/CollisionDetection/NarrowPhase.cs#L550) when running the [SimpleSelfContainedDemo](https://github.com/bepu/bepuphysics2/blob/master/Demos/Demos/SimpleSelfContainedDemo.cs) sample.

The exact place where the arithmetic overflow occur is at the [very end of the file named: NarrowPhase.cs](https://github.com/bepu/bepuphysics2/blob/76d3398ea6c9bd47626214abd157b3dcaaf965df/BepuPhysics/CollisionDetection/NarrowPhase.cs#L550).
[On line 550](https://github.com/bepu/bepuphysics2/blob/76d3398ea6c9bd47626214abd157b3dcaaf965df/BepuPhysics/CollisionDetection/NarrowPhase.cs#L550), the casting `(int)continuationIndex.Packed` is where the overflow occur.
The value of `continuationIndex.Packed` is `int.MaxValue + 1` and end up as an int with value: -2147483648.

Is this expected?  Perhaps the demo sample is out of date or something?

```cs
543 |    if (!continuationIndex.Exists)
544 |    {
545 |        //No CCD continuation was created, so create a discrete one.
546 |        continuationIndex = overlapWorker.Batcher.Callbacks.AddDiscrete(ref pair);
547 |        overlapWorker.Batcher.Add(
548 |            aCollidable.Shape, bCollidable.Shape,
549 |            poseB.Position - poseA.Position, poseA.Orientation, poseB.Orientation, velocityA, velocityB,
550 |            speculativeMargin, maximumExpansion, new PairContinuation((int)continuationIndex.Packed));
551 |    }

```

**Comment by RossNordby** [comment]
Yup, it's expected. Is there a reason you need to have overflow checking enabled?

**Comment by Bartolomeus-649** [comment]
I normally turn it on for debug builds.
The reason is to catch overflows while developing and testing.

If I come across a situation where I want or don't care if there's an overflow, I use the c# [unchecked ](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/unchecked) keyword. I kind of like to manually "opt-in" if I'm OK with something overflowing.

**Comment by RossNordby** [comment]
I'd recommend leaving it off for the bepuphysics project then. Integers are very frequently used in non-arithmetic ways that are expected to overflow harmlessly.

**Comment by Bartolomeus-649** [comment]
ok, So you don't have to worry about inputing data to bepuphysics that can cause internal overflows?

**Comment by RossNordby** [comment]
I won't claim it to be impossible, but I can't think of anywhere off the top of my head where integer overflow would be a concern. I've certainly never seen it, nor seen a report. Integers are very rarely used as anything but counts, indices, handles, and bitfields, all with pretty heavy asserts.

Bad floating point values, on the other hand, are a common issue.
