### ISSUE TITLE
Compile error CS8370 using  ChildOverlapsCollection as TypeArg

### ISSUE THREAD

**Issue by CharlesWoodhill** [bepu/bepuphysics2#92]
hello,
im getting the compile error
CS8370 C# Feature is not available in C# 7.3. Please use language version 8.0 or greater.
the feature it mourns about is "unmanaged constructed types" not possible in 7.3

i try to implement
`ICompoundPairContinuationHandler.CreateContinuation()`
this method has the parameter: 
`ref Buffer<ChildOverlapsCollection> pairOverlaps`

since it doesnt throw this error when i compile your demos,
i suspect that it is because i target net standard 2.0
the demo targets net core 2.1
iirc both only use C# 7.3 so im out of ideas ...
maybe some other workaround for this exists?
im bound to that implementation, since the parameter of the method im implementing 
is not declared with Interface , its declared with the struct itself.

one thing i noticed is that when i comment out that buffer field:
``` 
public unsafe struct ChildOverlapsCollection : ICollisionTaskSubpairOverlaps
{
        //public Buffer<int> Overlaps;
        public int Count;
        public int ChildIndex;
        ....
```
then the compiler doesnt run on error at my implementation,
altough ofc it mourns about the struct itself :)

using vs2019, and parts of xenko/stride3d thats why i currently bound to net standard 2.0

**Comment by RossNordby** [comment]
You can use C# 8.0 in .NET Standard 2.0, but the default is 7.3. For example, BepuPhysics.csproj specifies `<LangVersion>latest</LangVersion>`.

.NET Standard 2.0 support for C# 8.0 *is* partial- default interface members aren't supported, and a couple of other features require nugets. Bepuphysics doesn't use any of those though.

**Comment by CharlesWoodhill** [comment]
ah thats a nice one, 
i tried to set it manually to c# 8.0, but got a bunch of errors then for the project dependencies :)
i just hope this doesnt intefere with xenko/stride3d :)
