### ISSUE TITLE
Deterministic simulation across multiple machines

### ISSUE THREAD

**Issue by nxrighthere** [bepu/bepuphysics2#94]
Hey, really great job you did here!

We are currently looking for a library (native or managed) suitable for deterministic simulations across machines. This one seems like a good code base for that. Our first step will be replacing all floats with integers (fixed-point math), but this will not be enough because from what I see stuff is multi-threaded here, so this may cause indeterminism as well (islands in particular).

I've read some issues related to the subject and would like to take into account your opinion/thoughts about this.

**Comment by RossNordby** [comment]
There's a Simulation.Deterministic flag which can be set to true for local determinism. It works with multithreading. Of course, it still requires all interactions with the engine (adds/removes and so on) to be done in bitwise identical order too.

Swapping all floats with integers is going to be a hideous task, unfortunately. Even more than usual- all the high frequency parts of the engine are explicitly vectorized. Maintaining anywhere close to original performance would be... not *impossible*, but godspeed to anyone who attempts it.

**Comment by nxrighthere** [comment]
Thanks for the input, that’s all I want to hear.

> Swapping all floats with integers is going to be a hideous task, unfortunately. Even more than usual- all the high frequency parts of the engine are explicitly vectorized. Maintaining anywhere close to original performance would be... not impossible, but godspeed to anyone who attempts it.

Agreed, but still better than implementing a 3D physics engine from the ground up...

Cheers.

**Comment by RossNordby** [comment]
A codegen note if you do decide to dive in: you might notice the vectorized portions use some very unwieldy patterns, like `Vector3Wide.Scale(in Vector3Wide v, in Vector<float> s, out Vector3Wide r)`, which make every single calculation [ridiculously verbose and suffering-prone](https://github.com/bepu/bepuphysics2/blob/master/BepuPhysics/CollisionDetection/DepthRefiner.cs#L206).

That's an artifact of operators not producing reasonable codegen on large structs in earlier JITs. If you're targeting .NET 5 and newer exclusively, you can very likely use operators and returns without fear. As always, check the resulting assembly, but if you're going to be rewriting a ridiculous amount of math anyway, might as well reduce your suffering where possible :)

**Comment by nxrighthere** [comment]
Thanks for the info, will take that into account.

**Comment by pajama** [comment]
@nxrighthere any progress on this?
We're using https://github.com/mattleibow/jitterphysics right now, and it was pretty easy to convert over to FP, but there are **a lot** of other issues with the library.

**Comment by nxrighthere** [comment]
As @RossNordby correctly mentioned, even a well-optimized fixed-point math library causes a massive performance drop. We ended up using non-deterministic state sync instead.

**Comment by pajama** [comment]
Ah darn. Thanks for the update!
