### ISSUE TITLE
Would this be able to find all vertcies from mesh A that is inside mesh B

### ISSUE THREAD

**Issue by Todilo** [bepu/bepuphysics2#95]
I have rather special use-case. I have a static mesh A. Then a mesh B which I rotate close to A. I want to detect when and preferably which vertices from mesh B that is inside mesh A. The rotation of mesh B is just like 1->90 degree rotation in 1 degree step so no "real" physics involved. Could bepuphysics2 do this?
(its a wpf helix toolkit with sharpdx application)

**Comment by RossNordby** [comment]
Meshes don't have volume in bepuphysics2, so this would require a little extra effort. It can detect contacts at triangle intersections, but any triangles that are fully inside another mesh and don't have surface contacts would need to be tested for containment explicitly. One option would be to cast a ray from the vertex position in some direction and count the number of intersections with the mesh surface. Barring numerical issues and assuming the meshes are closed and manifold, if it's odd, then it's inside; if it's even, it's outside.
