### ISSUE TITLE
Wrong Assert when changing Shape

### ISSUE THREAD

**Issue by FlaXxy1** [bepu/bepuphysics2#99]
Version: latest (eef2ea98c1548a196f737cba2d5c93009ab5249b)

Reproduce: When a body has a Shape and you call `BodyReference.SetShape(default)`.

Expected: The Body should not have a shape any more.

Issue: The Assert pops up, because it checks the new ShapeIndex.

https://github.com/bepu/bepuphysics2/blob/eef2ea98c1548a196f737cba2d5c93009ab5249b/BepuPhysics/Bodies.cs#L151

**Comment by RossNordby** [comment]
Should be fixed in 59cc7007941221c35d2224e9c1bc1895f5da193a. Thanks for the report!

**Comment by FlaXxy1** [comment]
Thanks!
Btw why did the Packed Field of the TypedIndex become public?
